import type { RoutineData } from '../types/routine';

export interface ColorOption {
  id: string;
  name: string;
  bgLight: string;
  borderLight: string;
  textLight: string;
  bgDark: string;
  borderDark: string;
  textDark: string;
  hex: string;
}

export const COLOR_PALETTE: ColorOption[] = [
  {
    id: 'indigo',
    name: 'Indigo Velvet',
    bgLight: 'bg-indigo-50 hover:bg-indigo-100/80',
    borderLight: 'border-indigo-300',
    textLight: 'text-indigo-900',
    bgDark: 'dark:bg-indigo-950/60 dark:hover:bg-indigo-900/50',
    borderDark: 'dark:border-indigo-700/60',
    textDark: 'dark:text-indigo-200',
    hex: '#6366f1',
  },
  {
    id: 'emerald',
    name: 'Emerald Mint',
    bgLight: 'bg-emerald-50 hover:bg-emerald-100/80',
    borderLight: 'border-emerald-300',
    textLight: 'text-emerald-900',
    bgDark: 'dark:bg-emerald-950/60 dark:hover:bg-emerald-900/50',
    borderDark: 'dark:border-emerald-700/60',
    textDark: 'dark:text-emerald-200',
    hex: '#10b981',
  },
  {
    id: 'violet',
    name: 'Royal Violet',
    bgLight: 'bg-purple-50 hover:bg-purple-100/80',
    borderLight: 'border-purple-300',
    textLight: 'text-purple-900',
    bgDark: 'dark:bg-purple-950/60 dark:hover:bg-purple-900/50',
    borderDark: 'dark:border-purple-700/60',
    textDark: 'dark:text-purple-200',
    hex: '#8b5cf6',
  },
  {
    id: 'amber',
    name: 'Warm Amber',
    bgLight: 'bg-amber-50 hover:bg-amber-100/80',
    borderLight: 'border-amber-300',
    textLight: 'text-amber-900',
    bgDark: 'dark:bg-amber-950/60 dark:hover:bg-amber-900/50',
    borderDark: 'dark:border-amber-700/60',
    textDark: 'dark:text-amber-200',
    hex: '#f59e0b',
  },
  {
    id: 'rose',
    name: 'Vibrant Rose',
    bgLight: 'bg-rose-50 hover:bg-rose-100/80',
    borderLight: 'border-rose-300',
    textLight: 'text-rose-900',
    bgDark: 'dark:bg-rose-950/60 dark:hover:bg-rose-900/50',
    borderDark: 'dark:border-rose-700/60',
    textDark: 'dark:text-rose-200',
    hex: '#f43f5e',
  },
  {
    id: 'cyan',
    name: 'Cyan Breeze',
    bgLight: 'bg-cyan-50 hover:bg-cyan-100/80',
    borderLight: 'border-cyan-300',
    textLight: 'text-cyan-900',
    bgDark: 'dark:bg-cyan-950/60 dark:hover:bg-cyan-900/50',
    borderDark: 'dark:border-cyan-700/60',
    textDark: 'dark:text-cyan-200',
    hex: '#06b6d4',
  },
  {
    id: 'orange',
    name: 'Sunset Orange',
    bgLight: 'bg-orange-50 hover:bg-orange-100/80',
    borderLight: 'border-orange-300',
    textLight: 'text-orange-900',
    bgDark: 'dark:bg-orange-950/60 dark:hover:bg-orange-900/50',
    borderDark: 'dark:border-orange-700/60',
    textDark: 'dark:text-orange-200',
    hex: '#f97316',
  },
  {
    id: 'blue',
    name: 'Ocean Blue',
    bgLight: 'bg-blue-50 hover:bg-blue-100/80',
    borderLight: 'border-blue-300',
    textLight: 'text-blue-900',
    bgDark: 'dark:bg-blue-950/60 dark:hover:bg-blue-900/50',
    borderDark: 'dark:border-blue-700/60',
    textDark: 'dark:text-blue-200',
    hex: '#3b82f6',
  },
  {
    id: 'fuchsia',
    name: 'Neon Fuchsia',
    bgLight: 'bg-fuchsia-50 hover:bg-fuchsia-100/80',
    borderLight: 'border-fuchsia-300',
    textLight: 'text-fuchsia-900',
    bgDark: 'dark:bg-fuchsia-950/60 dark:hover:bg-fuchsia-900/50',
    borderDark: 'dark:border-fuchsia-700/60',
    textDark: 'dark:text-fuchsia-200',
    hex: '#d946ef',
  },
  {
    id: 'teal',
    name: 'Teal Forest',
    bgLight: 'bg-teal-50 hover:bg-teal-100/80',
    borderLight: 'border-teal-300',
    textLight: 'text-teal-900',
    bgDark: 'dark:bg-teal-950/60 dark:hover:bg-teal-900/50',
    borderDark: 'dark:border-teal-700/60',
    textDark: 'dark:text-teal-200',
    hex: '#14b8a6',
  },
];

export const CATEGORIES = [
  'Lecture',
  'Lab',
  'Tutorial',
  'Meeting',
  'Deep Work',
  'Self Study',
  'Workout',
  'Break',
  'Exam',
  'Personal',
];

export const DEFAULT_UNIVERSITY_ROUTINE: RoutineData = {
  version: 1,
  title: 'Spring 2026 Academic Timetable',
  subtitle: 'Department of Computer Science & Engineering',
  days: [
    { id: 'day-mon', name: 'Monday', shortName: 'Mon' },
    { id: 'day-tue', name: 'Tuesday', shortName: 'Tue' },
    { id: 'day-wed', name: 'Wednesday', shortName: 'Wed' },
    { id: 'day-thu', name: 'Thursday', shortName: 'Thu' },
    { id: 'day-fri', name: 'Friday', shortName: 'Fri' },
  ],
  timeSlots: [
    { id: 'slot-1', startTime: '08:30', endTime: '09:45', label: 'Period 1' },
    { id: 'slot-2', startTime: '10:00', endTime: '11:15', label: 'Period 2' },
    { id: 'slot-3', startTime: '11:30', endTime: '12:45', label: 'Period 3' },
    { id: 'slot-break', startTime: '12:45', endTime: '01:30', label: 'Lunch Recess', isBreak: true },
    { id: 'slot-4', startTime: '01:30', endTime: '02:45', label: 'Period 4' },
    { id: 'slot-5', startTime: '03:00', endTime: '04:15', label: 'Period 5' },
  ],
  items: [
    {
      id: 'item-1',
      dayId: 'day-mon',
      timeSlotId: 'slot-1',
      title: 'Data Structures & Algorithms',
      subtitle: 'CSE-201',
      location: 'Auditorium 201',
      instructor: 'Prof. Turing',
      color: 'indigo',
      category: 'Lecture',
    },
    {
      id: 'item-2',
      dayId: 'day-mon',
      timeSlotId: 'slot-2',
      title: 'Database Management Systems',
      subtitle: 'CSE-305',
      location: 'Room 402',
      instructor: 'Dr. Codd',
      color: 'emerald',
      category: 'Lecture',
    },
    {
      id: 'item-3',
      dayId: 'day-mon',
      timeSlotId: 'slot-4',
      title: 'Algorithms Practicum Lab',
      subtitle: 'CSE-202L',
      location: 'Software Lab 3',
      instructor: 'Eng. Lovelace',
      color: 'violet',
      category: 'Lab',
    },
    {
      id: 'item-4',
      dayId: 'day-tue',
      timeSlotId: 'slot-1',
      title: 'Linear Algebra & Calculus',
      subtitle: 'MATH-201',
      location: 'Hall B',
      instructor: 'Dr. Euler',
      color: 'amber',
      category: 'Lecture',
    },
    {
      id: 'item-5',
      dayId: 'day-tue',
      timeSlotId: 'slot-3',
      title: 'Computer Networks',
      subtitle: 'CSE-315',
      location: 'Room 308',
      instructor: 'Dr. Cerf',
      color: 'cyan',
      category: 'Lecture',
    },
    {
      id: 'item-6',
      dayId: 'day-wed',
      timeSlotId: 'slot-2',
      title: 'Operating Systems Internals',
      subtitle: 'CSE-320',
      location: 'Room 105',
      instructor: 'Prof. Torvalds',
      color: 'rose',
      category: 'Lecture',
    },
    {
      id: 'item-7',
      dayId: 'day-wed',
      timeSlotId: 'slot-4',
      title: 'OS Kernel & Concurrency Lab',
      subtitle: 'CSE-321L',
      location: 'Systems Lab 1',
      instructor: 'Eng. Ritchie',
      color: 'orange',
      category: 'Lab',
    },
    {
      id: 'item-8',
      dayId: 'day-thu',
      timeSlotId: 'slot-1',
      title: 'Data Structures & Algorithms',
      subtitle: 'CSE-201',
      location: 'Auditorium 201',
      instructor: 'Prof. Turing',
      color: 'indigo',
      category: 'Lecture',
    },
    {
      id: 'item-9',
      dayId: 'day-thu',
      timeSlotId: 'slot-3',
      title: 'Software Engineering Project',
      subtitle: 'CSE-400',
      location: 'Design Studio 2',
      instructor: 'Dr. Hamilton',
      color: 'teal',
      category: 'Tutorial',
    },
    {
      id: 'item-10',
      dayId: 'day-fri',
      timeSlotId: 'slot-2',
      title: 'Artificial Intelligence & Ethics',
      subtitle: 'CSE-450',
      location: 'Virtual Hall A',
      instructor: 'Dr. Russell',
      color: 'blue',
      category: 'Lecture',
    },
    {
      id: 'item-11',
      dayId: 'day-fri',
      timeSlotId: 'slot-4',
      title: 'Open Source Contribution Club',
      subtitle: 'ACM Club',
      location: 'Student Lounge',
      instructor: 'Student Leads',
      color: 'fuchsia',
      category: 'Self Study',
    },
  ],
  settings: {
    dayColumnPosition: 'right', // User explicitly requested rightmost column for days!
    theme: 'indigo',
    darkMode: false,
    compactMode: false,
    showLocation: true,
    showInstructor: true,
    showCategory: true,
    timeFormat: '12h',
  },
};

export const WORK_PRODUCTIVITY_ROUTINE: RoutineData = {
  version: 1,
  title: 'Engineering Sprint & Focus Schedule',
  subtitle: 'Fullstack Product Team',
  days: [
    { id: 'day-mon', name: 'Monday', shortName: 'Mon' },
    { id: 'day-tue', name: 'Tuesday', shortName: 'Tue' },
    { id: 'day-wed', name: 'Wednesday', shortName: 'Wed' },
    { id: 'day-thu', name: 'Thursday', shortName: 'Thu' },
    { id: 'day-fri', name: 'Friday', shortName: 'Fri' },
  ],
  timeSlots: [
    { id: 'w-1', startTime: '09:00', endTime: '10:00', label: 'Standup & Planning' },
    { id: 'w-2', startTime: '10:00', endTime: '12:30', label: 'Deep Focus Block 1' },
    { id: 'w-break', startTime: '12:30', endTime: '01:30', label: 'Lunch & Recharge', isBreak: true },
    { id: 'w-3', startTime: '01:30', endTime: '03:30', label: 'Deep Focus Block 2' },
    { id: 'w-4', startTime: '03:30', endTime: '04:30', label: 'Team Sync & PRs' },
    { id: 'w-5', startTime: '04:30', endTime: '05:30', label: 'Wrap-up & Learning' },
  ],
  items: [
    {
      id: 'w-item-1',
      dayId: 'day-mon',
      timeSlotId: 'w-1',
      title: 'Sprint Kickoff & Planning',
      subtitle: 'Sprint 24',
      location: 'Zoom / Room A',
      instructor: 'Product Lead',
      color: 'indigo',
      category: 'Meeting',
    },
    {
      id: 'w-item-2',
      dayId: 'day-mon',
      timeSlotId: 'w-2',
      title: 'Core Architecture Refactoring',
      subtitle: 'Engine v2',
      location: 'IDE',
      instructor: 'Self',
      color: 'emerald',
      category: 'Deep Work',
    },
    {
      id: 'w-item-3',
      dayId: 'day-tue',
      timeSlotId: 'w-2',
      title: 'Frontend UI/UX Polish',
      subtitle: 'Design System',
      location: 'Figma & React',
      instructor: 'Self',
      color: 'rose',
      category: 'Deep Work',
    },
    {
      id: 'w-item-4',
      dayId: 'day-wed',
      timeSlotId: 'w-4',
      title: 'Architecture Review & Demo',
      subtitle: 'All-Hands',
      location: 'Conference Room',
      instructor: 'Staff Engineer',
      color: 'violet',
      category: 'Meeting',
    },
    {
      id: 'w-item-5',
      dayId: 'day-fri',
      timeSlotId: 'w-5',
      title: 'Weekly Retro & Celebration',
      subtitle: 'Beer & Wins',
      location: 'Team Lounge',
      instructor: 'Team',
      color: 'amber',
      category: 'Break',
    },
  ],
  settings: {
    dayColumnPosition: 'right',
    theme: 'emerald',
    darkMode: false,
    compactMode: false,
    showLocation: true,
    showInstructor: true,
    showCategory: true,
    timeFormat: '12h',
  },
};

export const BLANK_ROUTINE: RoutineData = {
  version: 1,
  title: 'My Custom Routine',
  subtitle: 'Click any cell to add classes, meetings or routines',
  days: [
    { id: 'day-mon', name: 'Monday', shortName: 'Mon' },
    { id: 'day-tue', name: 'Tuesday', shortName: 'Tue' },
    { id: 'day-wed', name: 'Wednesday', shortName: 'Wed' },
    { id: 'day-thu', name: 'Thursday', shortName: 'Thu' },
    { id: 'day-fri', name: 'Friday', shortName: 'Fri' },
    { id: 'day-sat', name: 'Saturday', shortName: 'Sat', isOffDay: true },
    { id: 'day-sun', name: 'Sunday', shortName: 'Sun', isOffDay: true },
  ],
  timeSlots: [
    { id: 'slot-1', startTime: '08:00', endTime: '09:00', label: 'Hour 1' },
    { id: 'slot-2', startTime: '09:00', endTime: '10:00', label: 'Hour 2' },
    { id: 'slot-3', startTime: '10:00', endTime: '11:00', label: 'Hour 3' },
    { id: 'slot-4', startTime: '11:00', endTime: '12:00', label: 'Hour 4' },
    { id: 'slot-break', startTime: '12:00', endTime: '01:00', label: 'Break', isBreak: true },
    { id: 'slot-5', startTime: '01:00', endTime: '02:00', label: 'Hour 5' },
    { id: 'slot-6', startTime: '02:00', endTime: '03:00', label: 'Hour 6' },
    { id: 'slot-7', startTime: '03:00', endTime: '04:00', label: 'Hour 7' },
  ],
  items: [],
  settings: {
    dayColumnPosition: 'right',
    theme: 'indigo',
    darkMode: false,
    compactMode: false,
    showLocation: true,
    showInstructor: true,
    showCategory: true,
    timeFormat: '12h',
  },
};

export const PRESET_ROUTINES: { id: string; name: string; description: string; data: RoutineData }[] = [
  {
    id: 'university',
    name: 'University Academic Routine',
    description: 'Perfect for students and professors with courses, labs, rooms, and lecturers.',
    data: DEFAULT_UNIVERSITY_ROUTINE,
  },
  {
    id: 'work',
    name: 'Work & Deep Focus Schedule',
    description: 'Built for professionals, engineers, and creatives with sprints, standups, and focus blocks.',
    data: WORK_PRODUCTIVITY_ROUTINE,
  },
  {
    id: 'blank',
    name: 'Blank Timetable (7 Days)',
    description: 'Clean slate with 7 days and 8 hourly slots to customize completely.',
    data: BLANK_ROUTINE,
  },
];
