import type { RoutineData } from '../types/routine';

export interface ColorOption {
  id: string;
  name: string;
  bg: string;
  border: string;
  text: string;
  hex: string;
}

export const COLOR_PALETTE: ColorOption[] = [
  {
    id: 'sage',
    name: 'Cozy Sage',
    bg: '#F0F5F1',
    border: '#8FA395',
    text: '#2D3B31',
    hex: '#5B7065',
  },
  {
    id: 'clay',
    name: 'Warm Clay',
    bg: '#FAF1ED',
    border: '#D89E82',
    text: '#4A2A1A',
    hex: '#B87352',
  },
  {
    id: 'sand',
    name: 'Oatmeal Sand',
    bg: '#F8F5EE',
    border: '#C9BCAB',
    text: '#3D362C',
    hex: '#9E8E7A',
  },
  {
    id: 'denim',
    name: 'Dusty Denim',
    bg: '#EFF4F8',
    border: '#93B0C4',
    text: '#223847',
    hex: '#5B7A8C',
  },
  {
    id: 'amber',
    name: 'Warm Honey',
    bg: '#FDF7EC',
    border: '#E0BA74',
    text: '#4D3814',
    hex: '#C68B45',
  },
  {
    id: 'lavender',
    name: 'Muted Heather',
    bg: '#F6F2F8',
    border: '#B39EB5',
    text: '#3C2E42',
    hex: '#886F91',
  },
  {
    id: 'rose',
    name: 'Antique Rose',
    bg: '#FAF0F2',
    border: '#D49BA8',
    text: '#4A232D',
    hex: '#B56B7D',
  },
  {
    id: 'olive',
    name: 'Forest Olive',
    bg: '#F3F6EC',
    border: '#A1B088',
    text: '#2E381C',
    hex: '#6E8055',
  },
  {
    id: 'slate',
    name: 'Warm Slate',
    bg: '#F2F4F5',
    border: '#9EA8AF',
    text: '#283036',
    hex: '#63707A',
  },
  {
    id: 'brick',
    name: 'Adobe Brick',
    bg: '#F9ECEC',
    border: '#D18E8E',
    text: '#4C2424',
    hex: '#B05E5E',
  },
];

export const CATEGORIES = [
  'Lecture',
  'Lab',
  'Tutorial',
  'Meeting',
  'Deep Work',
  'Self Study',
  'Workout',
  'Break',
  'Personal',
];

export const DEFAULT_UNIVERSITY_ROUTINE: RoutineData = {
  version: 1,
  title: 'Academic Semester Timetable',
  subtitle: 'Faculty of Computer Science & Engineering',
  days: [
    { id: 'day-mon', name: 'Monday', shortName: 'Mon' },
    { id: 'day-tue', name: 'Tuesday', shortName: 'Tue' },
    { id: 'day-wed', name: 'Wednesday', shortName: 'Wed' },
    { id: 'day-thu', name: 'Thursday', shortName: 'Thu' },
    { id: 'day-fri', name: 'Friday', shortName: 'Fri' },
  ],
  timeSlots: [
    { id: 'slot-1', startTime: '08:30', endTime: '09:45', label: 'Period 1' },
    { id: 'slot-2', startTime: '10:00', endTime: '11:15', label: 'Period 2' },
    { id: 'slot-3', startTime: '11:30', endTime: '12:45', label: 'Period 3' },
    { id: 'slot-break', startTime: '12:45', endTime: '01:30', label: 'Lunch Recess', isBreak: true },
    { id: 'slot-4', startTime: '01:30', endTime: '02:45', label: 'Period 4' },
    { id: 'slot-5', startTime: '03:00', endTime: '04:15', label: 'Period 5' },
  ],
  items: [
    {
      id: 'item-1',
      dayId: 'day-mon',
      timeSlotId: 'slot-1',
      title: 'Data Structures & Algorithms',
      subtitle: 'CS-201',
      location: 'Hall 201',
      instructor: 'Prof. Turing',
      color: 'sage',
      category: 'Lecture',
    },
    {
      id: 'item-2',
      dayId: 'day-mon',
      timeSlotId: 'slot-2',
      title: 'Database Management Systems',
      subtitle: 'CS-305',
      location: 'Room 402',
      instructor: 'Dr. Codd',
      color: 'clay',
      category: 'Lecture',
    },
    {
      id: 'item-3',
      dayId: 'day-mon',
      timeSlotId: 'slot-4',
      title: 'Algorithms Practicum Lab',
      subtitle: 'CS-202L',
      location: 'Software Lab 3',
      instructor: 'Eng. Lovelace',
      color: 'lavender',
      category: 'Lab',
    },
    {
      id: 'item-4',
      dayId: 'day-tue',
      timeSlotId: 'slot-1',
      title: 'Linear Algebra & Calculus',
      subtitle: 'MATH-201',
      location: 'Auditorium B',
      instructor: 'Dr. Euler',
      color: 'amber',
      category: 'Lecture',
    },
    {
      id: 'item-5',
      dayId: 'day-tue',
      timeSlotId: 'slot-3',
      title: 'Computer Networks',
      subtitle: 'CS-315',
      location: 'Room 308',
      instructor: 'Dr. Cerf',
      color: 'denim',
      category: 'Lecture',
    },
    {
      id: 'item-6',
      dayId: 'day-wed',
      timeSlotId: 'slot-2',
      title: 'Operating Systems Internals',
      subtitle: 'CS-320',
      location: 'Room 105',
      instructor: 'Prof. Torvalds',
      color: 'rose',
      category: 'Lecture',
    },
    {
      id: 'item-7',
      dayId: 'day-wed',
      timeSlotId: 'slot-4',
      title: 'OS Kernel & Systems Lab',
      subtitle: 'CS-321L',
      location: 'Systems Lab 1',
      instructor: 'Eng. Ritchie',
      color: 'sand',
      category: 'Lab',
    },
    {
      id: 'item-8',
      dayId: 'day-thu',
      timeSlotId: 'slot-1',
      title: 'Data Structures & Algorithms',
      subtitle: 'CS-201',
      location: 'Hall 201',
      instructor: 'Prof. Turing',
      color: 'sage',
      category: 'Lecture',
    },
    {
      id: 'item-9',
      dayId: 'day-thu',
      timeSlotId: 'slot-3',
      title: 'Software Design Studio',
      subtitle: 'CS-400',
      location: 'Studio 2',
      instructor: 'Dr. Hamilton',
      color: 'olive',
      category: 'Tutorial',
    },
    {
      id: 'item-10',
      dayId: 'day-fri',
      timeSlotId: 'slot-2',
      title: 'Artificial Intelligence & Ethics',
      subtitle: 'CS-450',
      location: 'Seminar Hall',
      instructor: 'Dr. Russell',
      color: 'denim',
      category: 'Lecture',
    },
    {
      id: 'item-11',
      dayId: 'day-fri',
      timeSlotId: 'slot-4',
      title: 'Open Source Reading Group',
      subtitle: 'Reading Circle',
      location: 'Library Wing B',
      instructor: 'Student Leads',
      color: 'brick',
      category: 'Self Study',
    },
  ],
  settings: {
    dayColumnPosition: 'right', // User explicit requirement: rightmost column will be days
    theme: 'indigo',
    darkMode: false, // Light theme only
    compactMode: false,
    showLocation: true,
    showInstructor: true,
    showCategory: true,
    timeFormat: '12h',
  },
};

export const WORK_PRODUCTIVITY_ROUTINE: RoutineData = {
  version: 1,
  title: 'Weekly Focus & Sprint Schedule',
  subtitle: 'Product Design & Engineering',
  days: [
    { id: 'day-mon', name: 'Monday', shortName: 'Mon' },
    { id: 'day-tue', name: 'Tuesday', shortName: 'Tue' },
    { id: 'day-wed', name: 'Wednesday', shortName: 'Wed' },
    { id: 'day-thu', name: 'Thursday', shortName: 'Thu' },
    { id: 'day-fri', name: 'Friday', shortName: 'Fri' },
  ],
  timeSlots: [
    { id: 'w-1', startTime: '09:00', endTime: '10:00', label: 'Standup & Planning' },
    { id: 'w-2', startTime: '10:00', endTime: '12:30', label: 'Focus Block 1' },
    { id: 'w-break', startTime: '12:30', endTime: '01:30', label: 'Lunch Break', isBreak: true },
    { id: 'w-3', startTime: '01:30', endTime: '03:30', label: 'Focus Block 2' },
    { id: 'w-4', startTime: '03:30', endTime: '04:30', label: 'Collaboration' },
    { id: 'w-5', startTime: '04:30', endTime: '05:30', label: 'Wrap-up & Review' },
  ],
  items: [
    {
      id: 'w-item-1',
      dayId: 'day-mon',
      timeSlotId: 'w-1',
      title: 'Weekly Sprint Kickoff',
      subtitle: 'Sprint 24',
      location: 'Meeting Room 1',
      instructor: 'Product Team',
      color: 'sage',
      category: 'Meeting',
    },
    {
      id: 'w-item-2',
      dayId: 'day-mon',
      timeSlotId: 'w-2',
      title: 'Core Engine Refactoring',
      subtitle: 'Module Architecture',
      location: 'Desk',
      instructor: 'Self',
      color: 'denim',
      category: 'Deep Work',
    },
    {
      id: 'w-item-3',
      dayId: 'day-tue',
      timeSlotId: 'w-2',
      title: 'Design Polish & User Flow',
      subtitle: 'Figma System',
      location: 'Studio',
      instructor: 'Self',
      color: 'clay',
      category: 'Deep Work',
    },
    {
      id: 'w-item-4',
      dayId: 'day-wed',
      timeSlotId: 'w-4',
      title: 'Cross-functional Review',
      subtitle: 'All-Hands Sync',
      location: 'Conference Room',
      instructor: 'Team Lead',
      color: 'lavender',
      category: 'Meeting',
    },
    {
      id: 'w-item-5',
      dayId: 'day-fri',
      timeSlotId: 'w-5',
      title: 'Weekly Retro & Coffee',
      subtitle: 'Wins & Reflection',
      location: 'Lounge',
      instructor: 'All',
      color: 'amber',
      category: 'Break',
    },
  ],
  settings: {
    dayColumnPosition: 'right',
    theme: 'emerald',
    darkMode: false,
    compactMode: false,
    showLocation: true,
    showInstructor: true,
    showCategory: true,
    timeFormat: '12h',
  },
};

export const BLANK_ROUTINE: RoutineData = {
  version: 1,
  title: 'My Custom Routine',
  subtitle: 'Click any cell to add events or habits',
  days: [
    { id: 'day-mon', name: 'Monday', shortName: 'Mon' },
    { id: 'day-tue', name: 'Tuesday', shortName: 'Tue' },
    { id: 'day-wed', name: 'Wednesday', shortName: 'Wed' },
    { id: 'day-thu', name: 'Thursday', shortName: 'Thu' },
    { id: 'day-fri', name: 'Friday', shortName: 'Fri' },
    { id: 'day-sat', name: 'Saturday', shortName: 'Sat', isOffDay: true },
    { id: 'day-sun', name: 'Sunday', shortName: 'Sun', isOffDay: true },
  ],
  timeSlots: [
    { id: 'slot-1', startTime: '08:00', endTime: '09:00', label: 'Hour 1' },
    { id: 'slot-2', startTime: '09:00', endTime: '10:00', label: 'Hour 2' },
    { id: 'slot-3', startTime: '10:00', endTime: '11:00', label: 'Hour 3' },
    { id: 'slot-4', startTime: '11:00', endTime: '12:00', label: 'Hour 4' },
    { id: 'slot-break', startTime: '12:00', endTime: '01:00', label: 'Break', isBreak: true },
    { id: 'slot-5', startTime: '01:00', endTime: '02:00', label: 'Hour 5' },
    { id: 'slot-6', startTime: '02:00', endTime: '03:00', label: 'Hour 6' },
  ],
  items: [],
  settings: {
    dayColumnPosition: 'right',
    theme: 'indigo',
    darkMode: false,
    compactMode: false,
    showLocation: true,
    showInstructor: true,
    showCategory: true,
    timeFormat: '12h',
  },
};

export const PRESET_ROUTINES: { id: string; name: string; description: string; data: RoutineData }[] = [
  {
    id: 'university',
    name: 'University Timetable',
    description: 'Clean academic schedule with courses, labs, rooms, and professors in cozy tones.',
    data: DEFAULT_UNIVERSITY_ROUTINE,
  },
  {
    id: 'work',
    name: 'Work & Focus Schedule',
    description: 'Comfortable daily workflow with sprint blocks, sync meetings, and recharge breaks.',
    data: WORK_PRODUCTIVITY_ROUTINE,
  },
  {
    id: 'blank',
    name: 'Blank Canvas (7 Days)',
    description: 'Empty timetable ready for your personal classes, habits, and tasks.',
    data: BLANK_ROUTINE,
  },
];
